// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gojar.proto

package gojar

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProxyURLRequest struct {
	ProxyToken           string   `protobuf:"bytes,1,opt,name=proxyToken,proto3" json:"proxyToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyURLRequest) Reset()         { *m = ProxyURLRequest{} }
func (m *ProxyURLRequest) String() string { return proto.CompactTextString(m) }
func (*ProxyURLRequest) ProtoMessage()    {}
func (*ProxyURLRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d738b230e7bb319, []int{0}
}

func (m *ProxyURLRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyURLRequest.Unmarshal(m, b)
}
func (m *ProxyURLRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyURLRequest.Marshal(b, m, deterministic)
}
func (m *ProxyURLRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyURLRequest.Merge(m, src)
}
func (m *ProxyURLRequest) XXX_Size() int {
	return xxx_messageInfo_ProxyURLRequest.Size(m)
}
func (m *ProxyURLRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyURLRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyURLRequest proto.InternalMessageInfo

func (m *ProxyURLRequest) GetProxyToken() string {
	if m != nil {
		return m.ProxyToken
	}
	return ""
}

type ProxyURLResponse struct {
	URL                  string   `protobuf:"bytes,1,opt,name=URL,proto3" json:"URL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyURLResponse) Reset()         { *m = ProxyURLResponse{} }
func (m *ProxyURLResponse) String() string { return proto.CompactTextString(m) }
func (*ProxyURLResponse) ProtoMessage()    {}
func (*ProxyURLResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d738b230e7bb319, []int{1}
}

func (m *ProxyURLResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyURLResponse.Unmarshal(m, b)
}
func (m *ProxyURLResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyURLResponse.Marshal(b, m, deterministic)
}
func (m *ProxyURLResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyURLResponse.Merge(m, src)
}
func (m *ProxyURLResponse) XXX_Size() int {
	return xxx_messageInfo_ProxyURLResponse.Size(m)
}
func (m *ProxyURLResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyURLResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyURLResponse proto.InternalMessageInfo

func (m *ProxyURLResponse) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func init() {
	proto.RegisterType((*ProxyURLRequest)(nil), "gojar.ProxyURLRequest")
	proto.RegisterType((*ProxyURLResponse)(nil), "gojar.ProxyURLResponse")
}

func init() {
	proto.RegisterFile("gojar.proto", fileDescriptor_3d738b230e7bb319)
}

var fileDescriptor_3d738b230e7bb319 = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xcf, 0xcf, 0x4a,
	0x2c, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0x0c, 0xb9, 0xf8, 0x03,
	0x8a, 0xf2, 0x2b, 0x2a, 0x43, 0x83, 0x7c, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xe4,
	0xb8, 0xb8, 0x0a, 0x40, 0x42, 0x21, 0xf9, 0xd9, 0xa9, 0x79, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c,
	0x41, 0x48, 0x22, 0x4a, 0x2a, 0x5c, 0x02, 0x08, 0x2d, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42,
	0x02, 0x5c, 0xcc, 0xa1, 0x41, 0x3e, 0x50, 0xc5, 0x20, 0xa6, 0x91, 0x13, 0x17, 0xb3, 0x63, 0x80,
	0xa7, 0x90, 0x35, 0x17, 0x07, 0x4c, 0xb1, 0x90, 0x98, 0x1e, 0xc4, 0x01, 0x68, 0x16, 0x4a, 0x89,
	0x63, 0x88, 0x43, 0x4c, 0x75, 0x62, 0x8f, 0x82, 0xb8, 0x32, 0x89, 0x0d, 0xec, 0x66, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xae, 0xbd, 0x3e, 0x74, 0xc2, 0x00, 0x00, 0x00,
}
